[package]
publish = false
edition = "2018"
name = "mod_dummy"
version = "0.1.0"
authors = ["Daniel Werner <dan.werner@gmail.com>"]

[features]
default = []
dynamic_lib = []

[lib]
name = "mod_dummy"
crate-type=["dylib"]

[dependencies]

[dependencies.game_state]
path = "../game_state"
