[package]
name = "game_state"
version = "0.1.0"
authors = ["Daniel Werner <dan.werner@gmail.com>"]

[features]
default = []
dynamic_lib = []

[lib]
name = "game_state"
crate-type=["rlib"]

[dependencies]
cgmath = "0.12"
image = "0.13"
time = "0.1"
winit = "0.6"
nom-obj = "0.1"
